defaultProject: movielens-project-494814
defaultLocation: us-central1
defaultDataset: movielens
defaultAssertionDataset: movielens_assertions
dataformCoreVersion: 3.0.52
vars:
    LOAD_GCS_BUCKET: movielens-inbound/movielens
    RAW_DATA: movielens_staging #this dataset is not created manually
    TARGET_DATA: movielens_gold #this dataset is not created manually